### ISSUE TITLE
/doctors/ajaxgetclass.html

### ISSUE THREAD

**Issue by YIminta** [pengpan/91160-cli#10]
好像160的接口关掉了，这个没有返回正常数据

**Comment by pengpan** [comment]
是的，官方关闭了，准备转移到另一个接口`/guahao/v1/pc/sch/dep`，正在修复中

**Comment by YIminta** [comment]
我昨天也用另外一个接口跑通了，从 dep/show/depid-{depid}.html获取的信息中拿{doctorId}下的{am,pm}中的schId进行dosubmit就可以，还有别的接口么

**Comment by pengpan** [comment]
目前现状
- 页面`/dep/show/depid-{}.html`，接口`/dep/getschmast/uid-{}/depid-{}/date-{}/p-0.html`已被禁用
- 页面`/dep/show/depid-{}.html`，接口`/guahao/v1/pc/sch/dep`能用
- 页面`/doctors/index/unit_id-{}/dep_id-0/docid-{}.html`，接口`/doctors/ajaxgetclass.html`已被禁用

**Comment by YIminta** [comment]
有没有考虑微信小程序https://weixin.91160.com，小程序上的接口好像都没问题

**Comment by pengpan** [comment]
没去研究，不知道好不好抓包

**Comment by YIminta** [comment]
![image](https://user-images.githubusercontent.com/50685567/169999906-1fc7af8f-aed7-442a-8e60-44c65676309e.png)
刷号时有时候会掉线，然后我在查询dept前判断了下登录状态，重新登录的时候获取tokens失败

**Comment by YIminta** [comment]
![image](https://user-images.githubusercontent.com/50685567/170001518-eeb4d12f-fe8e-4d90-868d-12843ace7865.png)
还有日志时区不对

**Comment by pengpan** [comment]
日志时区是对的，我还没打包

**Comment by pengpan** [comment]
[v1.0.2](https://github.com/pengpan/91160-cli/releases/tag/v1.0.2): 日志时区和刷号判断登录已修复

**Comment by YIminta** [comment]
Register类登录成功后，没有AccountStore.store(userName, password)，后续登录状态过期重新登录报错用户名为空。

**Comment by YIminta** [comment]
![image](https://user-images.githubusercontent.com/50685567/170407992-83ebb441-a1ff-4428-8ce9-13c24a4f8d3c.png)
刷号持续25分钟左右登录状态会失效然后重新登录获取tokens失败。

**Comment by YIminta** [comment]
![image](https://user-images.githubusercontent.com/50685567/170429277-17ddd70c-fd1f-475b-98c4-eac593460776.png)
![image](https://user-images.githubusercontent.com/50685567/170429208-c10948b1-5834-484b-b061-91a47d2e00ae.png)
加上IP代理后请求报错

**Comment by pengpan** [comment]
> ![图片](https://user-images.githubusercontent.com/50685567/170408308-887ac876-55a6-4f46-aa1f-c8c6881442dd.png)
> 
> 刷号持续25分钟左右登录状态会失效，然后重新登录令牌失败。

哈哈，大意了，没测试到位

**Comment by pengpan** [comment]
> 

你这个代理有没有效哦，报连接超时，我去试下

**Comment by YIminta** [comment]
> > 
> 
> 你这个代理有没有效哦，报连接超时，我去试下

可以登录成功就是有效的吧

**Comment by pengpan** [comment]
卡在了dep那个接口，难道接口还能不允许别人用代理

**Comment by pengpan** [comment]
@YIminta 我想了解下大概刷多久什么样的频率会触发IP受限

**Comment by YIminta** [comment]
> @YIminta 我想了解下大概刷多久什么样的频率会触发IP受限

频率我没改，就是加了个代理IP，然后登录成功后开始挂号马上就报错了，

**Comment by YIminta** [comment]
> > @YIminta 我想了解下大概刷多久什么样的频率会触发IP受限
> 
> 平台接口的话10s以下的频率会触发IP受限直接掉线

但是app端的接口好像不会掉线，手指猛点都没事......

**Comment by pengpan** [comment]
好的，后期考虑改成app端接口
