### ISSUE TITLE
没有参数返回，怎么办

### ISSUE THREAD

**Issue by Xingzai2021** [pengpan/91160-cli#11]
160没有返回doctors的参数，/dep/getschmast 403拒绝访问了，请问大佬有没有办法

**Comment by pengpan** [comment]
`/doctors/ajaxgetclass.html`这个刷号接口确实被官方禁用了，只能转移到另一个接口上去了，目前正在修复中

**Comment by Xingzai2021** [comment]
收到，大佬辛苦了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: pengpan ***@***.***&gt;
发送时间: 2022年5月23日 10:50
收件人: pengpan/91160-cli ***@***.***&gt;
抄送: Xingzai2021 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [pengpan/91160-cli] 没有参数返回，怎么办 (Issue #11)





 
/doctors/ajaxgetclass.html这个刷号接口确实被官方禁用了，只能转移到另一个接口上去了，目前正在修复中

**Comment by Xingzai2021** [comment]
请问要在程序里对接ip代理池要怎么做



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: pengpan ***@***.***&gt;
发送时间: 2022年5月23日 10:50
收件人: pengpan/91160-cli ***@***.***&gt;
抄送: Xingzai2021 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [pengpan/91160-cli] 没有参数返回，怎么办 (Issue #11)





 
/doctors/ajaxgetclass.html这个刷号接口确实被官方禁用了，只能转移到另一个接口上去了，目前正在修复中

**Comment by pengpan** [comment]
网络请求走代理就行

**Comment by pengpan** [comment]
后面也会考虑加进去

**Comment by Xingzai2021** [comment]
我附件了截图，就是我放了ip在proxy里，但是访问测试网站返回来的还是我的ip



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: pengpan ***@***.***&gt;
发送时间: 2022年6月2日 01:09
收件人: pengpan/91160-cli ***@***.***&gt;
抄送: Xingzai2021 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [pengpan/91160-cli] 没有参数返回，怎么办 (Issue #11)





 
？

**Comment by pengpan** [comment]
看不到图片

**Comment by Xingzai2021** [comment]
发自我的iPhone


------------------ 原始邮件 ------------------
发件人: pengpan ***@***.***&gt;
发送时间: 2022年6月2日 01:19
收件人: pengpan/91160-cli ***@***.***&gt;
抄送: Xingzai2021 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [pengpan/91160-cli] 没有参数返回，怎么办 (Issue #11)





 
看不到图片

**Comment by pengpan** [comment]
看不到，你去github上回复
