### ISSUE TITLE
咨询大佬，如何添加非公立的医院呢？

### ISSUE THREAD

**Issue by Maoao530** [pengpan/91160-cli#19]
搜不到非公立的其他医院，比如深圳木棉花医院。

备孕中，想给老婆抢这个医生的号。询问博主如何支持，感谢！
https://www.91160.com/doctors/index/docid-200551928.html

config手动输入医院和医生的信息也不行：
    'unit_id': '200076552', #

**Comment by pengpan** [comment]
这个链接打开获取不到信息，有deptId吗？具体哪个科室？

**Comment by Maoao530** [comment]
应该是这个链接：https://www.91160.com/dep/show/depid-200249295.html

医院：深圳市木棉花健康医疗有限公司木棉花门诊部   'unit_id': '200076552', #
科室：生殖 • 妇科 • 中医   'dep_id': '200249295', #
医生：眭茜   'doc_id': '200551928', #

**Comment by pengpan** [comment]
用这个配置，我试了下是可以刷号的
```properties
# 91160账号
userName=[your userName]
# 91160密码
password=[your password]
# 就诊人编号
memberId=[your memberId]
# 城市编号
cityId=5
# 医院编号
unitId=200076552
# 大科室编号
bigDeptId=1
# 小科室编号
deptId=200249295
# 医生编号
doctorId=200551928
# 需要周几的号[可多选，如(6,7)]
weeks=1,2,3,4,5,6,7
# 时间段编号[可多选，如(am,pm)]
days=am,pm
# 刷号休眠时间[单位:秒]
sleepTime=5
```

**Comment by Maoao530** [comment]
感谢大佬，程序确实可以刷了。再请教一下哈，因为这个医生的号，是提前两周放号。比如5.30号17：00点放6.14的号。看log请求返回的都是本周的，有没有办法可以抢未来2周或者某个日期的号呢？

如果可以，那么我的config要怎么配置呢？
# 需要周几的号[可多选，如(6,7)]
weeks=2
# 时间段编号[可多选，如(am,pm)]
days=am,am
# 刷号休眠时间[单位:秒]
sleepTime=15
# 是否开启定时挂号[true/false]
enableAppoint=true
# 定时挂号时间[格式: 2022-06-01 15:00:00]   ==》 是改这里？
appointTime=2022-06-14 15:00:00

**Comment by pengpan** [comment]
因为刷号接口一次只会返回一周的号，我今天会加一个配置：起始刷号日期，填上这个日期就可以去刷这个日期后一周的号。
如你需要6.14的号，那起始刷号日期为6.8，weeks就填6.14对应的2（周二）即可。
appointTime为定时挂号时间，这个是表示会在设定的时间才开启抢票，也就是医院放号的时间，你也可以设置成5.30 17:00

**Comment by Maoao530** [comment]
这也太好了吧！！

术业有专攻，感谢大佬！

**Comment by pengpan** [comment]
[v1.0.6](https://github.com/pengpan/91160-cli/releases/tag/v1.0.6)，增加自定义刷号起始日期
```properties
# 刷号起始日期(表示刷该日期后一周的号,为空取当前日期)[格式: 2022-06-01]
brushStartDate=
```
