### ISSUE TITLE
Windows Terminal 和 cmd 中文乱码

### ISSUE THREAD

**Issue by seryte** [pengpan/91160-cli#33]
<img width="705" alt="image" src="https://user-images.githubusercontent.com/17977783/173995169-497e8302-af83-4991-885d-030aeaf02ebc.png">

**Comment by pengpan** [comment]
ref: [windows终端中文乱码如何解决](https://github.com/pengpan/91160-cli#windows%E7%BB%88%E7%AB%AF%E4%B8%AD%E6%96%87%E4%B9%B1%E7%A0%81%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3)

**Comment by seryte** [comment]
> ref: [windows终端中文乱码如何解决](https://github.com/pengpan/91160-cli#windows%E7%BB%88%E7%AB%AF%E4%B8%AD%E6%96%87%E4%B9%B1%E7%A0%81%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3)

抱歉, 没有认真读readme, 感谢

**Comment by seryte** [comment]
> ref: [windows终端中文乱码如何解决](https://github.com/pengpan/91160-cli#windows%E7%BB%88%E7%AB%AF%E4%B8%AD%E6%96%87%E4%B9%B1%E7%A0%81%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3)
这个Dfile也是个jar吗, 要下载吗
<img width="971" alt="image" src="https://user-images.githubusercontent.com/17977783/173996130-c5a32109-5d8e-4947-bd58-eab279719236.png">

**Comment by pengpan** [comment]
> > ref: [windows终端中文乱码如何解决](https://github.com/pengpan/91160-cli#windows%E7%BB%88%E7%AB%AF%E4%B8%AD%E6%96%87%E4%B9%B1%E7%A0%81%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3)
> 
> 这个Dfile也是个jar吗, 要下载吗
> 
> <img width="971" alt="image" src="https://user-images.githubusercontent.com/17977783/173996130-c5a32109-5d8e-4947-bd58-eab279719236.png">
> 
> 

不用

**Comment by pengpan** [comment]
> > > ref: [windows终端中文乱码如何解决](https://github.com/pengpan/91160-cli#windows%E7%BB%88%E7%AB%AF%E4%B8%AD%E6%96%87%E4%B9%B1%E7%A0%81%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3)
> > 
> > 这个Dfile也是个jar吗, 要下载吗
> > 
> > <img width="971" alt="image" src="https://user-images.githubusercontent.com/17977783/173996130-c5a32109-5d8e-4947-bd58-eab279719236.png">
> > 
> > 
> 
> 不用

不要用powershell，用cmd

**Comment by seryte** [comment]
> > > ref: [windows终端中文乱码如何解决](https://github.com/pengpan/91160-cli#windows%E7%BB%88%E7%AB%AF%E4%B8%AD%E6%96%87%E4%B9%B1%E7%A0%81%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3)
> > 
> > 这个Dfile也是个jar吗, 要下载吗
> > 
> > <img width="971" alt="image" src="https://user-images.githubusercontent.com/17977783/173996130-c5a32109-5d8e-4947-bd58-eab279719236.png">
> > 
> > 
> 
> 不用

那这个咋回事呢

**Comment by seryte** [comment]
> > > > ref: [windows终端中文乱码如何解决](https://github.com/pengpan/91160-cli#windows%E7%BB%88%E7%AB%AF%E4%B8%AD%E6%96%87%E4%B9%B1%E7%A0%81%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3)
> > > 
> > > 
> > > 这个Dfile也是个jar吗, 要下载吗
> > > <img alt="image" width="971" src="https://user-images.githubusercontent.com/17977783/173996130-c5a32109-5d8e-4947-bd58-eab279719236.png">
> > 
> > 
> > 不用
> 
> 不要用powershell，用cmd

`cmd `也是乱码, 而且进行了[这个](https://blog.csdn.net/qq_45373920/article/details/122521894)配置, 看是去是`stdout`本身不支持utf-8
```
Unable to get Charset 'cp65001' for property 'sun.stdout.encoding', using default GBK and continuing.
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
Unable to get Charset 'cp65001' for property 'sun.stdout.encoding', using default GBK and continuing.
```
<img width="907" alt="image" src="https://user-images.githubusercontent.com/17977783/174003752-cb7fb33a-9653-4055-ae54-9a969374fcb5.png">

**Comment by pengpan** [comment]
不用参考vscode配置，直接在cmd操作

1. 打开 cmd
2. 执行 chcp 65001
3. 执行 java -Dfile.encoding=utf-8 -jar 91160-cli.jar init|register

```shell
Active code page: 65001

C:\Users\W9012327\Desktop\91160-cli-1.1.1>java -Dfile.encoding=utf-8 -jar 91160-cli.jar init
Unable to get Charset 'cp65001' for property 'sun.stdout.encoding', using default UTF-8 and continuing.
请输入用户名: xxx
请输入密码:
2022-06-16 14:22:43.053  INFO : 登录中，请稍等...
2022-06-16 14:22:43.618  INFO : --> GET https://user.91160.com/login.html
```

**Comment by pengpan** [comment]
如何还是不行，换台电脑试试

**Comment by seryte** [comment]
> 不用参考vscode配置，直接在cmd操作
> 
> 1. 打开 cmd
> 2. 执行 chcp 65001
> 3. 执行 java -Dfile.encoding=utf-8 -jar 91160-cli.jar init|register
> 
> ```shell
> Active code page: 65001
> 
> C:\Users\XXX\Desktop\91160-cli-1.1.1>java -Dfile.encoding=utf-8 -jar 91160-cli.jar init
> Unable to get Charset 'cp65001' for property 'sun.stdout.encoding', using default UTF-8 and continuing.
> 请输入用户名: xxx
> 请输入密码:
> 2022-06-16 14:22:43.053  INFO : 登录中，请稍等...
> 2022-06-16 14:22:43.618  INFO : --> GET https://user.91160.com/login.html
> ```

感谢大佬， 这样可以了，实际还可以通过日志来看输出， 不是乱码

**Comment by pengpan** [comment]
对的，也可以通过日志文件查看
