### ISSUE TITLE
504 Gateway Time-out 然后终止了

### ISSUE THREAD

**Issue by seryte** [pengpan/91160-cli#37]
![image](https://user-images.githubusercontent.com/17977783/174707342-cde1e5ee-d871-4c66-b884-ac58674b36a0.png)

**Comment by seryte** [comment]
> 好的，会尽快修复

@pengpan 顺带请教一下,源码如何运行的? 入口文件是哪一个呀

**Comment by pengpan** [comment]
App.java

**Comment by seryte** [comment]
> App.java

用`javac App.java` 编译提示一堆包不存在呢

![image](https://user-images.githubusercontent.com/17977783/174804992-46726a35-15e3-4a3a-8a2b-fc01b1f5d055.png)

**Comment by pengpan** [comment]
> > App.java
> 
> 用`javac App.java` 编译提示一堆包不存在呢
> 
> ![image](https://user-images.githubusercontent.com/17977783/174804992-46726a35-15e3-4a3a-8a2b-fc01b1f5d055.png)

不是这样的，要在idea中运行，需要加载依赖的

**Comment by pengpan** [comment]
> ![image](https://user-images.githubusercontent.com/17977783/174707342-cde1e5ee-d871-4c66-b884-ac58674b36a0.png)

已修复 fixed #37
