### ISSUE TITLE
能不能用来着/是否有交流群

### ISSUE THREAD

**Issue by hushiyong15** [pengpan/91160-cli#39]
能不能用来着/是否有交流群

**Comment by hushiyong15** [comment]
交流群发一下，那个图片打不开

**Comment by happyin123** [comment]
有新的二维码吗，这个过期了，加群的小伙伴帮忙拉我一下，谢谢 @pengpan

**Comment by pengpan** [comment]
> 有新的二维码吗，这个过期了，加群的小伙伴帮忙拉我一下，谢谢 @pengpan 

![image](https://user-images.githubusercontent.com/13047947/184629663-e070a6ea-d172-497f-9503-705575edef1f.jpeg)

**Comment by happyin123** [comment]
选择上下午那一项就闪退，什么情况？ @pengpan

**Comment by pengpan** [comment]
> 选择上下午那一项就闪退，什么情况？ @pengpan 

提供下日志
