### ISSUE TITLE
请求增加功能:可选挂号时间跨度超过一周

### ISSUE THREAD

**Issue by BikerDuality** [pengpan/91160-cli#53]
有些医院放号是两周甚至三周

**Comment by pengpan** [comment]
可以将刷号起始日期设置放号的前一周，[设置刷号起始日期](https://github.com/pengpan/91160-cli#%E8%AE%BE%E7%BD%AE%E5%88%B7%E5%8F%B7%E8%B5%B7%E5%A7%8B%E6%97%A5%E6%9C%9F)
