### ISSUE TITLE
关于刷新间隔及负载影响

### ISSUE THREAD

**Issue by yang3121099** [pengpan/91160-cli#56]
非常感谢作者，我每天定闹钟抢票已经一个多月了，手动刷票即使没有失误也很难抢到

想问一下这个刷新间隔设置为多少比较合适，频繁请求是否会对健康160这个网站造成影响？同时也好奇频繁刷新是否会让自己的账号被风控和封禁等后果？

再次感谢！

**Comment by yang3121099** [comment]
补充，间隔50ms已经被制裁了，看来还是放票的时候用几分钟吧，不能一直挂着

**Comment by pengpan** [comment]
刷新间隔按照场景设置，如定点抢号建议设置小点（500），捡漏建议设置大点（5000）；
频繁请求会对91160官网造成压力，所以网站会对IP进行限制或封禁，可以使用IP代理绕过
