### ISSUE TITLE
请问如何停止刷号？以及刷到号怎么通知？

### ISSUE THREAD

**Issue by huangx5** [pengpan/91160-cli#64]
成功运行，感谢作者！

**Comment by chorem** [comment]
请问运行很顺利吗

**Comment by weimo123** [comment]
通知这一层，可以依赖官方的挂号成功短信。也可以考虑对接下消息推送通道，比如[Server酱](https://sct.ftqq.com/r/2737)

**Comment by pengpan** [comment]
可以考虑加入





------------------ 原始邮件 ------------------
发件人: weimo123 ***@***.***&gt;
发送时间: 2024年8月2日 13:33
收件人: pengpan/91160-cli ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [pengpan/91160-cli] 请问如何停止刷号？以及刷到号怎么通知？ (Issue #64)





 
通知这一层，可以依赖官方的挂号成功短信。也可以考虑对接下消息推送通道，比如Server酱

**Comment by pengpan** [comment]
最新版已支持 ServerChan 通知
