### ISSUE TITLE
非常感谢大神开发

### ISSUE THREAD

**Issue by bupbedepxinh** [pengpan/91160-cli#8]
有个疑问，如果我配置周六周日挂号，就只能设置为本周六周日，而不包含下一周的周六日，是不是就是这样的？能不能改进下

**Comment by pengpan** [comment]
是这样的，后面会改成具体的日期

**Comment by creazy412** [comment]
> 是这样的，后面会改成具体的日期

备注：刷号起始日期(表示刷该日期后一周的号,为空取当前日期)

有个疑问：为空则取当前日期，那这时刷的下周六日的号，还是本周六日号呢？
比如我想刷下周6月18、19号（周六、周日）的号源，那开始日期是指定“本周”的“任意一天”即可，是这样理解吗？

**Comment by creazy412** [comment]
如果默认取当前日期，那这时刷的下周的号，那本周号不就刷不了吗？

**Comment by pengpan** [comment]
刷号起始日期(包含)+6天，这就是刷号的日期范围
