### ISSUE TITLE
提示用户名密码错误

### ISSUE THREAD

**Issue by wushibudaidao** [pengpan/91160-cli#9]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by retrofit2.Platform (file:/C:/Users/Administrator/Desktop/CleanMyWechat/91160-cli.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
登录失败，请检查用户名密码

**Comment by pengpan** [comment]
看了报错信息，应该是JDK版本不对，建议使用JDK1.8

**Comment by wushibudaidao** [comment]
使用1.8后不报错但是提示登录失败，请检查用户名密码

**Comment by pengpan** [comment]
你去[https://user.91160.com](https://user.91160.com)上面试下，看登录要不要其他验证

**Comment by wushibudaidao** [comment]
无需验证

**Comment by pengpan** [comment]
你用[最新版](https://github.com/pengpan/91160-cli/releases/tag/v1.0.1)试下，会有接口请求日志打印，贴下日志再分析下
